require 'buildr/as3'

custom_layout = Layout::Default.new
custom_layout[:source,:main,:as3] = "src"
custom_layout[:source,:test,:as3] = "test"

define "Directory-layouts", :layout => custom_layout do

  compile.using :mxmlc,
                :flexsdk => FlexSDK.new("4.5.0.20967"),
                :main => _(:src,"Main.as")

end