require "buildr/as3"

define "UsingSourceLibraries" do

  compile.using :mxmlc,
                :flexsdk => FlexSDK.new("4.5.0.20967"),
                :main => _(:source, :main, :as3, "Main.as")

  compile.from _(:lib,:main,:as3,:RedCircle)

end